# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-19 14:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estore', '0007_auto_20170715_0251'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='items',
        ),
    ]
