# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-13 11:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estore', '0009_auto_20170813_0603'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together=set([('product', 'cart')]),
        ),
    ]
